# Generated by Django 2.2.16 on 2020-10-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('blood_bag_num', models.AutoField(primary_key=True, serialize=False)),
                ('blood_type', models.CharField(max_length=5)),
                ('blood_units', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
            },
        ),
    ]
