# Generated by Django 2.2.16 on 2020-10-20 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodinventory',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blood_donor', to='users.Donor'),
        ),
        migrations.AddField(
            model_name='bloodinventory',
            name='recipient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blood_recipient', to='users.Recipient'),
        ),
        migrations.AddField(
            model_name='bloodinventory',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blood_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
